graphql:
  build: .
  ports:
    - '4000:4000'
  volumes:
    - .:/home/app/graphql
    - /home/app/graphql/node_modules
  extra_hosts:
    - "dockerhost:$DOCKERHOST"
  environment:
    ELASTICSEARCH_HOST: $DOCKERHOST
    ELASTICSEARCH_PORT: 9200
